### ISSUE TITLE
move react to peerDeps

### ISSUE THREAD

**Issue by Guria** [rebem/rebem#4]
React dependency could cause 2 react instances installed:
https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375#.wvy7xpwn2

**Comment by Guria** [comment]
would be great to release new version after merge

**Comment by mistadikay** [comment]
@Guria thanks for PR, but I don't think that removing React from dependency list when we [use it directly](https://github.com/rebem/rebem/blob/master/lib/index.js#L10) is correct. If you're trying to use `rebem` with `react@15.0.0-rc.1`, we can change the React dependency into `0.14.x || >=15.0.0-rc.1`, so React@15 would be supported. In this case, depending on what you use in your project, React@0.14 or React@15 would be installed (only one instance, because our dependency is loose). Below is an example of what you'll have in your dependencies list:
```
├─┬ react@15.0.0-rc.1
│ ├─┬ envify@3.4.0
│ │ ├─┬ jstransform@10.1.0
│ │ │ ├── base62@0.1.1
│ │ │ ├── esprima-fb@13001.1001.0-dev-harmony-fb
│ │ │ └─┬ source-map@0.1.31
│ │ │   └── amdefine@1.0.0
│ │ └── through@2.3.8
│ └─┬ fbjs@0.8.0-alpha.3
│   ├─┬ babel-plugin-syntax-flow@6.5.0
│   │ └── babel-runtime@5.8.35
│   ├── core-js@1.2.6
│   ├─┬ isomorphic-fetch@2.2.1
│   │ ├─┬ node-fetch@1.3.3
│   │ │ └─┬ encoding@0.1.12
│   │ │   └── iconv-lite@0.4.13
│   │ └── whatwg-fetch@0.11.0
│   ├─┬ loose-envify@1.1.0
│   │ └── js-tokens@1.0.2
│   ├─┬ promise@7.1.1
│   │ └── asap@2.0.3
│   └── ua-parser-js@0.7.10
├── react-dom@15.0.0-rc.1
└─┬ rebem@0.7.0
  └── rebem-classname@0.1.0
```

**Comment by Guria** [comment]
> I don't think that removing React from dependency list when we use it directly

it is not removed. Just moved to peerDependencies and devDependencies. It is absolutely correct use case. React will be used peer from project when `rebem` installed as dependency and will be installed from dev dependency when run `npm i` in rebem itself.

> we can change the React dependency into `0.14.x || >=15.0.0-rc.1`

I can updatemy PR,s to extend supported versions of course

**Comment by Guria** [comment]
@mistadikay npm sometimes decides to install separate versions of react even with compatible ranges. Only `rm -rf node_modules && npm i` helps in that case. React doesn't always detects several instances of itself what leads to unwanted debugging:
http://stackoverflow.com/questions/30451556/what-is-the-correct-way-of-adding-a-dependency-to-react-in-your-package-json-for
https://www.google.ru/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#newwindow=1&safe=off&q=Move+react+to+peerDependencies

**Comment by deepsweet** [comment]
react-router [doesn't have](https://github.com/reactjs/react-router/blob/master/package.json) React neither in normal nor peer deps ¯\\_(ツ)_/¯

**Comment by mistadikay** [comment]
yeah, I just noticed that `react-dnd` doesn't have React as a dependency too, though it uses it directly. So, yeah, let's do it. @Guria please take a look at the comment in your PR
