### ISSUE TITLE
Props in child is empty object

### ISSUE THREAD

**Issue by vitaliyzolotoy** [rebem/rebem#8]
Props from Block in not available in children block:
Parent block:
```javascript
render() {
    return Block(
        this.props,
        Plan()
    );
}
```

Children block:
```javascript
export default class Plans extends Component {
    constructor(props) {
        super(props);

        console.log(this.props); // {}
    }
}
```

**Comment by deepsweet** [comment]
Because it should not work that way – React doesn't automagically pass
parent's props to the children.

Your example is (almost) the same as `<Block {...this.props}><Plan/></Block>
`
